---

 - hosts: all
   become: true
   tasks:

     - name: update repositories
       dnf: 
         update_cache: yes
         when: ansible_distro == "centos"

     - name: update repositories
       apt:
         update_cache: yes
         when: ansible_distro == "ubuntu"
     
